# Generated by Django 4.2.6 on 2023-11-20 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0002_alter_userinfo_height_alter_userinfo_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="metabolism",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
