# Generated by Django 4.2.6 on 2023-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
