# Generated by Django 4.2.6 on 2023-11-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_email_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
