# Generated by Django 4.2.6 on 2023-11-20 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_password_reset_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="metabolism",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
