# Generated by Django 4.2.6 on 2023-12-21 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be at least 6 characters and contain only letters and numbers.",
                        regex="^(?=.*[a-zA-Z0-9]).{6,}$",
                    )
                ],
            ),
        ),
    ]
