# Generated by Django 4.2.6 on 2023-12-21 02:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=128, validators=[accounts.models.validate_password]
            ),
        ),
    ]
