# Generated by Django 4.2.6 on 2023-11-10 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cal", models.FloatField()),
                ("amount_per_serving", models.FloatField()),
                ("carbohydrate", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("sugars", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("salt", models.FloatField(blank=True, null=True)),
                ("sodium", models.FloatField(blank=True, null=True)),
                ("potassium", models.FloatField(blank=True, null=True)),
                ("calcium", models.FloatField(blank=True, null=True)),
                ("magnesium", models.FloatField(blank=True, null=True)),
                ("iron", models.FloatField(blank=True, null=True)),
                ("zinc", models.FloatField(blank=True, null=True)),
                ("vitamin_a", models.FloatField(blank=True, null=True)),
                ("vitamin_d", models.FloatField(blank=True, null=True)),
                ("vitamin_e", models.FloatField(blank=True, null=True)),
                ("vitamin_b1", models.FloatField(blank=True, null=True)),
                ("vitamin_b2", models.FloatField(blank=True, null=True)),
                ("vitamin_b12", models.FloatField(blank=True, null=True)),
                ("vitamin_b6", models.FloatField(blank=True, null=True)),
                ("vitamin_c", models.FloatField(blank=True, null=True)),
                ("niacin", models.FloatField(blank=True, null=True)),
                ("cholesterol", models.FloatField(blank=True, null=True)),
                ("saturated_fat", models.FloatField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_date", models.DateField()),
                ("serving", models.FloatField(blank=True, null=True)),
                ("grams", models.FloatField(blank=True, null=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "朝食"),
                            ("lunch", "昼食"),
                            ("dinner", "夕食"),
                            ("snack", "スナック"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal.food"
                    ),
                ),
            ],
        ),
    ]
