# Generated by Django 4.2.6 on 2023-11-20 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0002_alter_food_amount_per_serving_alter_food_cal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="amount_per_serving",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="cal",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
