# Generated by Django 4.2.6 on 2023-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0003_alter_food_amount_per_serving_alter_food_cal"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="food_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="is_open_api",
            field=models.BooleanField(default=False),
        ),
    ]
