# Generated by Django 4.2.6 on 2023-11-22 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0004_food_food_id_food_is_open_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="is_100g",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="food",
            name="is_serving",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="food",
            name="amount_per_serving",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
