# Generated by Django 4.2.6 on 2023-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0002_alter_exercise_memos_alter_workout_workout_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="duration_minutes",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="mets",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
