# Generated by Django 4.2.6 on 2023-11-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0003_alter_exercise_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="d_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
