# Generated by Django 4.2.6 on 2023-11-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0004_workout_d_id_workout_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="default_workout",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exercise.workout"
            ),
        ),
    ]
