# Generated by Django 4.2.6 on 2023-12-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0005_remove_exercise_default_workout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("Aerobic", "Aerobic"),
                    ("Chest", "Chest"),
                    ("Shoulder", "Shoulder"),
                    ("Back", "Back"),
                    ("Leg", "Leg"),
                    ("Arm", "Arm"),
                    ("Abs", "Abs"),
                    ("Other", "Other"),
                    ("Living", "Living"),
                ],
                max_length=20,
            ),
        ),
    ]
