# Generated by Django 4.2.6 on 2023-11-30 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grow",
                    models.CharField(
                        choices=[
                            ("Egg", "Egg"),
                            ("Egg2", "Egg2"),
                            ("Baby", "Baby"),
                            ("Child", "Child"),
                            ("Adult", "Adult"),
                        ],
                        default="Egg",
                        max_length=10,
                    ),
                ),
                (
                    "body_status",
                    models.CharField(
                        choices=[
                            ("Egg", "Egg"),
                            ("Egg2", "Egg2"),
                            ("Baby", "Baby"),
                            ("Child", "Child"),
                            ("Adult", "Adult"),
                        ],
                        default="Muscular",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
