# Generated by Django 4.2.6 on 2023-12-01 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="user",
            new_name="account",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="body_status",
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[
                    ("Fatting", "Fatting"),
                    ("Thin", "Thin"),
                    ("Muscular", "Muscular"),
                ],
                default="Thin",
                max_length=10,
            ),
        ),
    ]
