# Generated by Django 4.2.6 on 2023-12-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0003_rename_status_pet_body_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="body_status",
            field=models.CharField(
                choices=[
                    ("Fatting", "Fatting"),
                    ("Semi-Fatting", "Semi-Fatting"),
                    ("Thin", "Thin"),
                    ("Semi-Thin", "Semi-Thin"),
                    ("Muscular", "Muscular"),
                    ("Normal", "Normal"),
                ],
                default="Thin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="grow",
            field=models.CharField(
                choices=[
                    ("Egg", "Egg"),
                    ("Egg2", "Egg2"),
                    ("Baby", "Baby"),
                    ("Baby2", "Baby2"),
                    ("Child", "Child"),
                    ("Child2", "Child2"),
                    ("Adult", "Adult"),
                    ("End", "End"),
                ],
                default="Egg",
                max_length=10,
            ),
        ),
    ]
