# Generated by Django 4.2.6 on 2023-12-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0004_alter_pet_body_status_alter_pet_grow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="body_status",
            field=models.CharField(
                choices=[
                    ("Fatting", "Fatting"),
                    ("Semi-Fatting", "Semi-Fatting"),
                    ("Thin", "Thin"),
                    ("Semi-Thin", "Semi-Thin"),
                    ("Semi-Muscular", "Semi-Muscular"),
                    ("Muscular", "Muscular"),
                    ("Normal", "Normal"),
                ],
                default="Thin",
                max_length=20,
            ),
        ),
    ]
